service: kore-api
useDotenv: true

plugins:
    - serverless-webpack
    - serverless-azure-functions
	
custom:
  resourcePrefix: 'kore-serverless'
provider:
    name: azure
    location: Japan East
    runtime: nodejs14
    stage: ${opt:stage, 'offline'}
    resourceGroup: ${self:custom.resourcePrefix}-${self:provider.stage}-rg
    appInsights:
        name: ${self:custom.resourcePrefix}-${self:provider.stage}-appinsights
    functionApp:
        name: ${self:custom.resourcePrefix}-${self:provider.stage}-funtionapp
    storageAccount:
        name: ${self:custom.resourcePrefix}-${self:provider.stage}-sa # Should be shorter than 24 characters

package:
    individually: false
    exclude:
        - package.json
        - node_modules/**
        - .gitignore
        - .git/**

functions:
    app:
        handler: src/handler.handler
        events:
            - http: true
              x-azure-settings:
                  authLevel: anonymous
                  route: '{*segments}'
                  methods:
                      - GET
                      - POST
                      - OPTIONS
            - http: true
              x-azure-settings:
                  direction: out
                  name: res
