service: kore-api
useDotenv: true

plugins:
    - serverless-webpack
    - serverless-azure-functions

provider:
    name: azure
    stage: ${opt:stage, 'offline'}
    location: 'Japan East'
    runtime: nodejs14

package:
    individually: false
    exclude:
        - package.json
        - node_modules/**
        - .gitignore
        - .git/**

functions:
    app:
        handler: src/handler.handler
        events:
            - http: true
              x-azure-settings:
                  authLevel: anonymous
                  route: '{*segments}'
                  methods:
                      - GET
                      - POST
                      - OPTIONS
            - http: true
              x-azure-settings:
                  direction: out
                  name: res
