name: Auto deploy API to AWS Lambda

on:
    push:
        paths-ignore:
            - 'src/views/**'
        branches:
            - master
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Install Dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - uses: actions/setup-python@v2
            - uses: aws-actions/setup-sam@v1
            - uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-southeast-1

            - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name kore-ts --s3-bucket aws-sam-lambda-bucket --capabilities CAPABILITY_IAM --region ap-southeast-1
