name: Auto deploy static files

on:
    push:
        paths:
            - 'public/**'
        branches:
            - master
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: 'Azure CLI login'
              uses: azure/actions/login@v1
              with:
                  creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

            - name: Run script file
              env:
                  API_URL: ${{ secrets.API_URL }}
              run: |
                  chmod +x ./scripts/*.sh
                  bash ./scripts/entrypoint.sh
              shell: bash

            - name: Deploy static files
              env:
                  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  AZURE_RESOURCE_PREFIX: ${{ secrets.AZURE_RESOURCE_PREFIX }}
                  STAGE: dev
              run: |
                  bash ./scripts/deployStatic.sh
              shell: bash
