name: Manual deploy static files

on: workflow_dispatch

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: 'Azure CLI login'
              uses: azure/actions/login@v1
              with:
                  creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

            - name: Run script file
              env:
                  API_URL: ${{ secrets.API_URL }}
              run: |
                  chmod +x ./scripts/entrypoint.sh
                  ./scripts/entrypoint.sh
              shell: bash

            - name: Deploy static files
              env:
                  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  RESOURCE_GROUP_NAME: sls-jape-dev-kore-api-rg
                  STORAGE_ACCOUNT_NAME: slsjapedevstatic
              run: |
                  chmod +x ./scripts/deployStatic.sh
                  ./scripts/deployStatic.sh
              shell: bash

            #- run: |
            #      az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            #      az configure -d group=sls-jape-dev-kore-api-rg
            #      az storage account create --name slsjapedevstatic
            #      az storage blob service-properties update --account-name slsjapedevstatic --static-website --404-document 404.html --index-document index.html
            #      az storage blob upload-batch --account-name slsjapedevstatic --overwrite true -s ./public -d '$web'
