name: Manual deploy static files

on: workflow_dispatch

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-southeast-1

            - name: Run script file
              env:
                  API_URL: ${{ secrets.API_URL }}
              run: |
                  chmod +x ./scripts/entrypoint.sh
                  ./scripts/entrypoint.sh
              shell: bash

            - run: aws s3 sync ./src/views s3://${{ secrets.AWS_S3_BUCKET_NAME }}
