name: Run testing

on:
    pull_request:
        types: [opened, synchronize]
        paths-ignore:
            - 'src/views/**'
    push:
        paths-ignore:
            - 'src/views/**'
        branches:
            - master

jobs:
    e2e-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'yarn'

            - name: Install Dependencies
              run: yarn install

            - name: Set up AWS
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-southeast-1

            - name: Setup local DynamoDB
              run: docker run -d -p 8000:8000 --name dynamodb amazon/dynamodb-local -jar DynamoDBLocal.jar -inMemory -sharedDb

            - name: Create table
              run: aws dynamodb create-table --cli-input-json file://json/createBookingDetailTable.json --endpoint-url http://localhost:8000

            - name: Run test
              run: yarn test
              env:
                  IS_OFFLINE: true
